OPENAI_API_KEY = "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"
ADMIN_TOKEN    = "maggi"
