OPENAI_API_KEY = "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"
ADMIN_TOKEN    = "maggi"
