OPENAI_API_KEY = "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"
ADMIN_TOKEN    = "maggi"
